4_django/instargram/accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('<int:user_id>/', views.user_page, name="user_page"),
    path('<int:user_id>/follow/', views.follow, name="follow"),
    path('<int:user_id>/update/', views.update, name="update")
]

4_django/instargram/instargram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from posts import views

urlpatterns = [
    path('', views.all),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4_django/instargram/posts/urls.py
from django.urls import path
from . import views



app_name = "posts"


urlpatterns = [
    # Read - 전체 글 보기
    path('', views.index, name="index"),
    path('all/', views.all, name="all"),
    # Create - 포스트 작성하기
    path('create/', views.create, name="create"),
    # Update - 포스트 수정하기
    path('<int:post_id>/update/', views.update, name='update'),
    # Delete - 포스트 삭제하기
    path('<int:post_id>/delete/', views.delete, name='delete'),

    # Comment_create
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),

    # like
    path('<int:post_id>/likes/', views.likes, name='likes'),

    # hashtag
    path('hashtags/<int:hashtag_id>/', views.hashtags, name='hashtags'),

    # javascript test
    path('test/', views.javascript)
]

4_django/instargram/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.


class User(AbstractUser):
    follow = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="follower")
    introduce = models.TextField(blank=True)   # 빈칸도 허용하겠다
    image = ProcessedImageField(
        upload_to='accounts/images',  # 올리는 위치 설정
        processors=[ResizeToFill(150, 150)],
        format='JPEG',
        options={'quality': 60},
        blank=True,
    )

4_django/instargram/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings


# Create your models here.

class Hashtag(models.Model):
    content = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.content


class Post(models.Model):
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    # image = models.ImageField(blank=True)
    image = ProcessedImageField(
                                upload_to='posts/images',    # 올리는 위치 설정
                                processors=[ResizeToFill(600, 600)],
                                format='JPEG',
                                options={'quality': 60}
    )
    hashtags = models.ManyToManyField(Hashtag, blank=True)


class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

4_django/instargram/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', ]


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ('email', 'introduce', 'image',)

4_django/instargram/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import User
from django.contrib.auth.decorators import login_required

# Create your views here.


def signup(request):
    if request.user.is_authenticated:
        return redirect("posts:index")
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login(request):
    if request.user.is_authenticated:
        return redirect("posts:index")
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout(request):
    auth_logout(request)
    return redirect('posts:index')


def user_page(request, user_id):
    user_info = User.objects.get(id=user_id)
    context = {
        'user_info': user_info
    }
    return render(request, 'accounts/user_page.html', context)


@login_required()
def follow(request, user_id):
    me = request.user
    you = User.objects.get(id=user_id)
    if me != you:
        if you in me.follow.all():
            me.follow.remove(you)
        else:
            me.follow.add(you)
    return redirect('accounts:user_page', user_id)


def update(request, user_id):
    me = request.user
    you = User.objects.get(id=user_id)
    if me == you:
        if request.method == "POST":
            form = CustomUserChangeForm(request.POST, request.FILES, instance=you)
            if form.is_valid():
                form.save()
                return redirect("accounts:user_page", user_id)
        else:
            form = CustomUserChangeForm(instance=you)
        return render(request, 'accounts/update.html', {'form': form})
    return redirect("posts:index")

4_django/instargram/accounts/templates/accounts/login.html
{% extends 'posts/base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-outline-primary" type="submit" value="로그인">
        <a href="{% provider_login_url 'kakao' %}">카카오 로그인</a>
    </form>
{% endblock %}

4_django/instargram/accounts/templates/accounts/signup.html
{% extends 'posts/base.html' %}
{% load bootstrap4 %}
{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-outline-primary" type="submit" value="회원가입">
    </form>
{% endblock %}

4_django/instargram/accounts/templates/accounts/update.html
{% extends 'posts/base.html' %}
{% load bootstrap4 %}
{% block body %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-outline-primary" type="submit" value="정보수정">
    </form>
{% endblock %}

4_django/instargram/accounts/templates/accounts/user_page.html
{% extends 'posts/base.html' %}

{% block body %}
<div class="row">
    <div class="col-4 d-flex justify-content-center">
        <!--프로필 이미지 넣는 공간-->
        {% if user_info.image %}
            <img src="{{ user_info.image.url }}" alt="profile_image" class="rounded-circle">
        {% else %}
            <img src="https://picsum.photos/id/{{user_info.id}}/300/300" alt="..." class="rounded-circle">
        {% endif %}
    </div>
    <div class="col-8">
        <!--개인정보가 보여지는 공간-->
        {{user_info.username}}
        {% if user != user_info %}
            {% if user_info in user.follow.all %}
                <a class="btn btn-outline-primary" href="{% url 'accounts:follow' user_info.id %}">팔로우 취소</a>
            {% else %}
                <a class="btn btn-outline-primary" href="{% url 'accounts:follow' user_info.id %}">팔로우</a>
            {% endif %}
        {% else %}
            <a class="btn btn-outline-primary" href="{% url 'accounts:update' user_info.id %}">개인정보수정</a>
        {% endif %}
        <div class="flex-direction: column">
            <p>게시물 {{user_info.post_set.count}}</p>
            <p>팔로우 {{user_info.follower.count}}</p>
            <p>팔로워 {{user_info.follow.count}}</p>
        </div>
        <div>
            {{user_info.introduce}}
        </div>
    </div>
</div>
<div class="card-columns">
    {% for post in user_info.post_set.all %}
        {% include 'posts/_post.html' %}
    {% endfor %}
</div>
{% endblock %}