4_django/instargram/accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('<int:user_id>/', views.user_page, name="user_page"),
    path('<int:user_id>/follow/', views.follow, name="follow"),
    path('<int:user_id>/update/', views.update, name="update")
]

4_django/instargram/instargram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from posts import views

urlpatterns = [
    path('', views.all),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4_django/instargram/posts/urls.py
from django.urls import path
from . import views



app_name = "posts"


urlpatterns = [
    # Read - 전체 글 보기
    path('', views.index, name="index"),
    path('all/', views.all, name="all"),
    # Create - 포스트 작성하기
    path('create/', views.create, name="create"),
    # Update - 포스트 수정하기
    path('<int:post_id>/update/', views.update, name='update'),
    # Delete - 포스트 삭제하기
    path('<int:post_id>/delete/', views.delete, name='delete'),

    # Comment_create
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),

    # like
    path('<int:post_id>/likes/', views.likes, name='likes'),

    # hashtag
    path('hashtags/<int:hashtag_id>/', views.hashtags, name='hashtags'),

    # javascript test
    path('test/', views.javascript)
]

4_django/instargram/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings


# Create your models here.

class Hashtag(models.Model):
    content = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.content


class Post(models.Model):
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    # image = models.ImageField(blank=True)
    image = ProcessedImageField(
                                upload_to='posts/images',    # 올리는 위치 설정
                                processors=[ResizeToFill(600, 600)],
                                format='JPEG',
                                options={'quality': 60}
    )
    hashtags = models.ManyToManyField(Hashtag, blank=True)


class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

4_django/instargram/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ['content', 'image']   # 컬럼중에 어떤 것을 보여줄지 선택하는 항목


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

4_django/instargram/posts/views.py
from django.shortcuts import render, redirect
from .forms import PostForm, CommentForm
from .models import Post, Hashtag
from django.contrib.auth.decorators import login_required
from itertools import chain
from django.http import JsonResponse
# Create your views here.


def index(request):
    user_follow = request.user.follow.all()
    follow_list = chain(user_follow, [request.user])
    posts = Post.objects.order_by('-id').filter(user__in=follow_list)
    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/index.html', context)


def all(request):
    posts = Post.objects.all().order_by('-id')
    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'posts/index.html', context)


def create(request):
    # 1. get 방식으로 데이터를 입력할 수 있는 form을 요청한다.
    # 4. 사용자가 데이터를 입력해서 post요청을 보낸다.
    # 9. 사용자가 적절한 데이터를 입력해서 post 요청을 보낸다.
    if request.method == "POST":
        # 5. post방식으로 저장요청을 받고, 데이터를 받아서 PostForm을 인스턴스화 한다.
        # 10. 데이터를 받아서 PostForm을 인스턴스화 한다.
        form = PostForm(request.POST, request.FILES)
        # 6. 데이터 검증을 한다.
        # 11. 데이터 검증을 한다
        if form.is_valid():
            # 12. 적절한 데이터가 들어온다. 저장을 하고 인덱스로 보낸다.
            post = form.save(commit=False)
            post.user = request.user
            post.save()


            # 해시태그 추가
            content = form.cleaned_data.get('content')     # request.POST.get 대신 사용, 데이터를 정리해준다
            words = content.split()
            for word in words:
                if word[0] == '#':
                    # 해시테그 생성
                    hashtag = Hashtag.objects.get_or_create(content=word)
                    # 해시테그와 포스트 연결
                    post.hashtags.add(hashtag[0])
            return redirect("posts:index")
        else:
            # 7. 적절하지 않은 데이터가 들어온다.
            pass
    else:
        # 2.PostForm을 인스턴스화 해서 form 변수에 저장
        form = PostForm()
    context = {
        'form': form,
    }
    # 3. 만들어진 form을 create.html에 담아서 전송
    # 8. 사용자가 정확하게 입력한 데이터를 유지한 상태의 form을 전송
    return render(request, 'posts/form.html', context)


@login_required
def update(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.user == post.user:
        # 내가 작성한 글일때
        if request.method == 'POST':
            form = PostForm(request.POST, instance=post)  # data = request.POST(기존데이터), instance (덮어씌울 데이터)
            if form.is_valid():
                form.save()

                # 기존의 헤쉬테그 삭제
                post.hashtags.clear()
                # 해시태그 추가
                content = form.cleaned_data.get('content')  # request.POST.get 대신 사용, 데이터를 정리해준다
                words = content.split()
                for word in words:
                    if word[0] == '#':
                        # 해시테그 생성
                        hashtag = Hashtag.objects.get_or_create(content=word)
                        # 해시테그와 포스트 연결
                        post.hashtags.add(hashtag[0])
                return redirect("posts:index")
            else:
                pass
        else:
            form = PostForm(instance=post)
        return render(request, 'posts/form.html', {'form': form})
    else:
        # 내가 작성하지 않은 글일때
        return redirect("posts:index")


def delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect("posts:index")


@login_required
def comment_create(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect('posts:index')


@login_required()
def likes(request, post_id):
    user = request.user
    post = Post.objects.get(id=post_id)
    # 이미 좋아요가 눌러졌으면 좋아요 취소
    if user in post.like_users.all():
        post.like_users.remove(user)
        is_like = False
    # 좋아요 안했으면 좋아요 추가
    else:
        post.like_users.add(user)
        is_like = True
    context = {
        'is_like': is_like
    }
    return JsonResponse(context)
    # return redirect('posts:index')


def hashtags(request, hashtag_id):
    hashtag = Hashtag.objects.get(id=hashtag_id)
    posts = hashtag.post_set.all()
    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form
    }
    return render(request, 'posts/index.html', context)


def javascript(request):
    return render(request, 'posts/js.html')

4_django/instargram/posts/templates/posts/_post.html
{% load bootstrap4 %}
{% load posts_templatetag %}
{% if request.resolver_match.url_name == 'index' %}
<div class="card col-12 col-md-6 my-3" >
{% else %}
<div class="card my-3">
{% endif %}
    {% if post.image %}
        <img src="{{post.image.url}}" class="card-img-top" alt="...">
    {% else %}
        <img src="https://picsum.photos/id/{{post.id}}/300/300" class="card-img-top" alt="...">
    {% endif %}
    <div class="card-body">
      <!--<h5 class="card-title">Card title</h5>-->
        <p class="card-text">{{post}}</p>
        <!--<a href="#" class="btn btn-primary">Go somewhere</a>-->
        <p>{{post.like_users.count}}명이 좋아합니다</p>
        <p class="card-text"><strong><a href="{% url 'accounts:user_page' post.user.id %}">{{post.user.username}}</a></strong>{{post|hashtag_link|safe}}</p>
        {% if user in post.like_users.all  %}
            <i class="fas fa-heart" style="color:red" data-id="{{post.id}}"></i>
        {% else %}
            <i class="far fa-heart" style="color:red" data-id="{{post.id}}"></i>
        {% endif %}

        {% if post.user == user %}
            <a class="btn btn-warning" href="{% url 'posts:update' post.id %}">수정</a>
            <a class="btn btn-danger" href="{% url 'posts:delete' post.id %}">삭제</a>
        {% endif %}
    </div>
    {% if request.resolver_match.url_name == 'index' %}
        <!--댓글 출력 시작-->
        <div class="card-body">
            {% for comment in post.comment_set.all %}
                <p><strong>{{comment.user.username}} : </strong>{{comment.content}}</p>
            {% empty %}
                <p>댓글이 없습니다.</p>
            {% endfor %}
        </div>
        <!--댓글 출력 끝-->
        <!--댓글 폼 시작-->
        <div class="card-body">
            <form action="{% url 'posts:comment_create' post.id %}" method="post">
                {% csrf_token %}
                {% bootstrap_form comment_form %}
                <input type="submit">
            </form>
        </div>
        <!--댓글 폼 끝-->
    {% endif %}
</div>

4_django/instargram/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/fce5c87797.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <i class="fab fa-instagram"></i> | Instargram
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'posts:all' %}">All <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link active" href="{% url 'posts:create' %}">New <span class="sr-only">(current)</span></a>
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">LogOut</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:user_page' user.id %}">{{user}}님 반갑습니다.</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">LogIn</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        const likeButtons = document.querySelectorAll('.fa-heart')
        likeButtons.forEach(function(button){
            button.addEventListener('click', (e)=>{
                const postId = e.target.dataset.id
                axios.get(`/posts/${postId}/likes/`)
                .then(function(res){
                    console.log(res)
                    if(res.data.is_like){
                        e.target.classList.remove('far')
                        e.target.classList.add('fas')
                        e.target.style.color = 'red'
                    }
                    else{
                        e.target.classList.remove('fas')
                        e.target.classList.add('far')
                        e.target.style.color = 'black'
                    }
                })
            })
        })
    </script>
</body>
</html>

4_django/instargram/posts/templates/posts/form.html
{% extends 'posts/base.html' %}
{% load bootstrap4 %}
{% block body %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
</form>

{% endblock %}

4_django/instargram/posts/templates/posts/index.html
{% extends 'posts/base.html' %}

{% block body %}
{% if request.resolver_match.url_name == 'index' %}
    <h1>index</h1>
{% elif request.resolver_match.url_name == 'all' %}
    <h1>전체목록</h1>
{% else %}
    <h1>{{hashtag.content}}</h1>
{% endif %}
{% for post in posts %}
    <div class="row">
        {% include 'posts/_post.html' %} <!--post.html 파일을 가져온다-->
    </div>
{% endfor %}
{% endblock %}

4_django/instargram/posts/templates/posts/js.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div id="me">

    </div>
    <button id="my-button">click</button>
    <script>
        const button = document.querySelector('#my-button')
        button.addEventListener('click', (e) => {
        const div = document.querySelector('#me')
        div.innerText = "하이하이"
        })
    </script>
</body>
</html>