4_django/board/articles/urls.py
from django.urls import path
from . import views


app_name = "articles"


urlpatterns = [
    # Read
    path('', views.index, name='index'),
    path('<int:article_id>', views.detail, name="detail"),

    # Create
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),

    # Delete
    path('<int:article_id>/delete', views.delete, name="delete"),

    # Update
    # path('<int:article_id>/edit/', views.edit, name="edit"),
    path('<int:article_id>/update/', views.update, name="update"),

    path('<int:article_id>/comments/create/', views.comment_create, name="comment_create"),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name="comment_delete"),

    path('comment_all/', views.comment_all, name="comment_all"),
]

4_django/board/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

4_django/board/articles/models.py
from django.db import models
from django.conf import settings
# Create your models here.
# settings.AUTH_USER_MODEL


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)  # 폭포수(CASCADE) 모델을 적용한다. 하위 요소가 상위 요소에 종속
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

4_django/board/articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment


def index(request):
    articles = Article.objects.all()
    context = {
        'articles':articles
    }
    return render(request, 'articles/index.html', context)


def detail(request, article_id):
    article = Article.objects.get(id=article_id)
    context = {
        'article':article
    }
    return render(request, 'articles/detail.html', context)


def new(request):
    pass


def create(request):
    if request.method == "POST":
        article = Article()
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.user = request.user
        article.save()
        return redirect('articles:detail', article.id)
    else:
        return render(request, 'articles/form.html')


def delete(request, article_id):
    article = Article.objects.get(id=article_id)
    article.delete()
    return redirect('articles:index')


def edit(request, article_id):
    pass


def update(request, article_id):
    if request.method == "POST":
        article = Article.objects.get(id=article_id)
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('articles:detail', article_id)
    else:
        article = Article.objects.get(id=article_id)
        context = {
            'article': article
        }
        return render(request, 'articles/form.html', context)


def comment_create(request, article_id):
    comment = Comment()
    article = Article.objects.get(id=article_id)
    comment.content = request.POST.get('content')
    comment.article = article
    comment.user = request.user
    comment.save()
    return redirect("articles:detail", article_id)


def comment_delete(request, article_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()

    return redirect('articles:detail', article_id)


def comment_all(request):
    return render(request, 'articles/comment_all.html')

4_django/board/articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'articles:index' %}">MYBoard</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'articles:create' %}">new <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link active" href="{% url 'articles:comment_all' %}">comment <span class="sr-only">(current)</span></a>
        </div>
    </div>
    </nav>
    <div class="container">
    {% block body %}
    {% endblock %}
    </div>
<!--사용자 로딩속도를 빠르게 느끼게 하기위해 오래걸리는 java는 뒤로 뺀다-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

4_django/board/articles/templates/articles/comment_all.html
{% extends 'articles/base.html' %}

{% block body %}
    <h1>로그인한 유저 : {{user}}</h1>
    {% for comment in user.comment_set.all %}
        <div class="alert alert-warning" role="alert">
            {{comment.content}}
        </div>
    {% endfor %}
{% endblock %}

4_django/board/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% block body %}
<div class="card" >
    <img src="https://picsum.photos/id/{{article.id}}/1000/100" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{article.title}}</h5>
        <p class="card-text">{{article.content}}</p>
        <a class="btn btn-warning" href="{% url 'articles:delete' article.id %}">삭제</a>
        <a class="btn btn-danger" href="{% url 'articles:update' article.id %}">수정</a>
    </div>
</div>

<form action="{% url 'articles:comment_create' article.id %}" method="post">
    {% csrf_token %}
  <div class="form-group">
    <label for="comment">댓글 작성</label>
    <input type="text" class="form-control" id="comment" aria-describedby="emailHelp" placeholder="댓글을 입력하세요" name="content">
  </div>

  <button type="submit" class="btn btn-primary">등록</button>
</form>
<div class="my-3">
    {% for comment in article.comment_set.all %}
    <div class="alert alert-success d-flex justify-content-between" role="alert">
      {{comment.user}} : {{comment.content}}
        <a class="btn btn-outline-danger" href="{% url 'articles:comment_delete' article.id comment.id %}">삭제</a>
    </div>
    {% endfor %}
</div>


{% endblock %}

4_django/board/articles/templates/articles/edit.html
{% extends 'articles/base.html' %}
{% block body %}
<form action="{% url 'articles:update' article.id %}" method="post">  <!--urls.py의 path name 을 참조한다.-->
    {% csrf_token %}   <!--post 요청에서 최소한의 보안을 위해-->
  <div class="form-group">
    <label for="title">제목</label>
    <input value="{{article.title}}" type="text" class="form-control" id="title" placeholder="제목을 적어주세요" name="title">
  </div>
  <div class="form-group">
    <label for="content">내용</label>
    <input value="{{article.content}}" type="text" class="form-control" id="content" placeholder="내용을 적어주세요" name="content">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

4_django/board/articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% block body %}
<form action="" method="post">  <!--urls.py의 path name 을 참조한다.-->
    {% csrf_token %}   <!--post 요청에서 최소한의 보안을 위해-->
  <div class="form-group">
    <label for="title">제목</label>
    <input value="{{article.title}}" type="text" class="form-control" id="title" placeholder="제목을 적어주세요" name="title">
  </div>
  <div class="form-group">
    <label for="content">내용</label>
    <input value="{{article.content}}" type="text" class="form-control" id="content" placeholder="내용을 적어주세요" name="content">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

4_django/board/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% block body %}
    <h1>여기는 인덱스 입니다</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">title</th>
          <th scope="col">content</th>
          <th scope="col">user</th>
          <th scope="col">method</th>
        </tr>

      </thead>
      <tbody>
        {% for article in articles %}
        <tr>
          <th scope="row">{{article.id}}</th>
          <td>{{article.title}}</td>
          <td>{{article.content}}</td>
          <td>{{article.user}}</td>
          <td>
              <a href="{% url 'articles:detail' article.id %}">글보기</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}

4_django/board/articles/templates/articles/new.html
{% extends 'articles/base.html' %}
{% block body %}
<form action="{% url 'articles:create' %}" method="post">  <!--urls.py의 path name 을 참조한다.-->
    {% csrf_token %}   <!--post 요청에서 최소한의 보안을 위해-->
  <div class="form-group">
    <label for="title">제목</label>
    <input type="text" class="form-control" id="title" placeholder="제목을 적어주세요" name="title">
  </div>
  <div class="form-group">
    <label for="content">내용</label>
    <input type="text" class="form-control" id="content" placeholder="내용을 적어주세요" name="content">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}